declare type HtmlToCanvasOptions = Partial<{ allowTaint: boolean, backgroundColor: CSSStyleDeclaration["color"]|null, scale: number, windowWidth: number, windowHeight: number }>;
declare function ym(counter: number, event: string, id: string): void;
declare function html2canvas(element: Element, options?: HtmlToCanvasOptions): Promise<HTMLCanvasElement>;
declare type Category = { type: 'CATEGORY'; [CATEGORY_TAG]?: string };
declare type Service = { type: 'SERVICE'; [SERVICE_NAME_TAG]?: string; [SERVICE_DESCRIPTION_TAG]?: string; [SERVICE_PRICE_TAG]?: string; };
declare type Items = (Category | Service)[];
declare type PagesStyle = Partial<{ aspectRatio: CSSStyleDeclaration["aspectRatio"] }>;
declare type Page = Partial<{ [TITLE_TAG]: string, ITEMS: Items, [FOOTER_TAG]: string, STYLE: Partial<CSSStyleDeclaration> }>;
declare type Pages = Partial<{ PAGES: Page[]; STYLE: PagesStyle }>;
declare type EditableTags = typeof TITLE_TAG | typeof FOOTER_TAG | typeof CATEGORY_TAG | typeof SERVICE_NAME_TAG | typeof SERVICE_PRICE_TAG | typeof SERVICE_DESCRIPTION_TAG ;
declare const MESSAGES: {
    [TITLE_TAG]: string;
    [CATEGORY_TAG]: string;
    [SERVICE_NAME_TAG]: string;
    [SERVICE_PRICE_TAG]: string;
    [SERVICE_DESCRIPTION_TAG]: string;
    [FOOTER_TAG]: string;
    EXAMPLE_TITLE: string;
    EXAMPLE_FOOTER: string;
    FILE_LOAD_ERROR: string;
    REMOVE_ELEMENT: string;
    REMOVE_PAGE: string;
    IMPORT_CONFIRM: string;
    LOAD_CONFIRM: string;
    PAGES: string;
};
declare const EXAMPLE_ITEMS: Items;
